IS.Store.UI/ViewModels/Conta/Login/LoginVM.cs
using System.ComponentModel.DataAnnotations;

namespace IS.Store.UI.ViewModels.Conta.Login
{
    public class LoginVM
    {
        [Required(ErrorMessage = "O {0} é obrigatório")]
        [StringLength(80, ErrorMessage = "O limite do {0} é de {1} caracteres.")]
        //[RegularExpression(@"([\w\.\-]+)((\.(\w){2,3})+)", ErrorMessage = "Email inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "O {0} é obrigatório")]
        [StringLength(50, ErrorMessage = "O limite do {0} é de {1} caracteres.")]
        public string Senha { get; set; }

        public bool PermanecerLogado { get; set; }

        public string ReturnUrl { get; set; }
    }
}

IS.Store.UI/ViewModels/Produtos/AddEdit/Maps/Extensions.cs
using IS.Store.Domain.Entities;

namespace IS.Store.UI.ViewModels.Produtos.AddEdit.Maps
{

    public static class Extensions
    {
        public static ProdutoAddEditVM ToProdutoAddEditVM(this Produto model)
        {
            return new ProdutoAddEditVM()
            {
                Id = model.Id,
                Nome = model.Nome,
                Preco = model.Preco,
                TipoDeProdutoId = model.TipoDeProdutoId,
                Qtde = model.Qtde,
                DataCadastro = model.DataCadastro
            };
        }

        public static Produto ToProduto(this ProdutoAddEditVM model)
        {
            return new Produto()
            {
                Id = model.Id,
                Nome = model.Nome,
                Preco = model.Preco,
                TipoDeProdutoId = model.TipoDeProdutoId,
                Qtde = model.Qtde,
                DataCadastro = model.DataCadastro
            };
        }
    }
}

IS.Store.UI/ViewModels/Produtos/AddEdit/ProdutoAddEditVM.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace IS.Store.UI.ViewModels.Produtos.AddEdit
{
    public class ProdutoAddEditVM
    {
        public ProdutoAddEditVM()
        {
            DataCadastro = DateTime.Now;
        }

        public int Id { get; set; }
        [Required, StringLength(100)]
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public short Qtde { get; set; }
        [Display(Name = "Tipo de produto")]
        public int TipoDeProdutoId { get; set; }
        public DateTime DataCadastro { get; set; }

    }
}

IS.Store.UI/ViewModels/Produtos/Index/Maps/Extensions.cs
using IS.Store.Domain.Entities;
using System.Collections.Generic;
using System.Linq;

namespace IS.Store.UI.ViewModels.Produtos.Index.Maps
{
    public static class Extensions
    {

        public static IEnumerable<ProdutoIndexVM> ToProdutoIndexVM(this IEnumerable<Produto> data)
        {
            return data.Select(p => new ProdutoIndexVM()
            {
                Id = p.Id,
                Nome = p.Nome,
                Preco = p.Preco,
                Tipo = p.TipoDeProduto.Nome,
                Qtde = p.Qtde,
                DataCadastro = p.DataCadastro
            });
        }
    }
}

IS.Store.UI/ViewModels/Produtos/Index/ProdutoIndexVM.cs
using System;

namespace IS.Store.UI.ViewModels.Produtos.Index
{
    public class ProdutoIndexVM
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public short Qtde { get; set; }
        public string Tipo { get; set; }
        public DateTime DataCadastro { get; set; } = DateTime.Now;

    }
}

IS.Store.UI/Controllers/ContaController.cs
using IS.Store.Domain.Contracts.Repositories;
using IS.Store.Domain.Helpers;
using IS.Store.UI.ViewModels.Conta.Login;
using System.Web.Mvc;
using System.Web.Security;

namespace IS.Store.UI.Controllers
{
    public class ContaController:Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public ContaController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        [HttpGet]
        public ActionResult Login(string ReturnUrl)
        {
            var model = new LoginVM { ReturnUrl = ReturnUrl };
            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginVM model)
        {
            var usuario = _usuarioRepository.Get(model.Email);
            if(usuario == null)
            {
                ModelState.AddModelError("Email", "O e-mail não foi localizado.");
            } else
            {
                if (usuario.Senha != model.Senha.Encrypt())
                {
                    ModelState.AddModelError("Senha", "Senha incorreta.");
                }
            }


            if (ModelState.IsValid)
            {
                FormsAuthentication.SetAuthCookie(model.Email, model.PermanecerLogado);
                if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
                {
                    return Redirect(model.ReturnUrl);
                }
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {}
    }
}

IS.Store.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace IS.Store.UI.Controllers
{
    public class HomeController:Controller
    {
        public ViewResult Index()
        {
            return View();
        }
        public ViewResult Sobre()
        {
            return View();
        }
    }
}

IS.Store.UI/Controllers/ProdutosController.cs
using IS.Store.Domain.Contracts.Repositories;
using System.Web.Mvc;
using IS.Store.UI.ViewModels.Produtos.Index.Maps;
using IS.Store.UI.ViewModels.Produtos.AddEdit.Maps;
using IS.Store.UI.ViewModels.Produtos.AddEdit;

namespace IS.Store.UI.Controllers
{
    [Authorize]
    public class ProdutosController:Controller
    {
        //variáveis private começam com _ (padrão)
        private readonly IProdutoRepository _produtoRepository;
        private readonly ITipoDeProdutoRepository _tipoDeProdutoRepository;

        public ProdutosController(
            IProdutoRepository produtoRepository, 
            ITipoDeProdutoRepository tipoDeProdutoRepository)
        { 
            _produtoRepository = produtoRepository;
            _tipoDeProdutoRepository = tipoDeProdutoRepository;
        }

        public ViewResult Index()
        {
            var produtos = _produtoRepository.Get().ToProdutoIndexVM();
            return View(produtos);
        }

        [HttpGet]
        public ViewResult AddEdit(int? id)
        {
            var produto = new ProdutoAddEditVM();
            if(id != null)
            {
                produto = _produtoRepository.Get((int)id).ToProdutoAddEditVM();
            }
            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;
            return View(produto);
        }

        [HttpPost]
        public ActionResult AddEdit(ProdutoAddEditVM produtoVM)
        {
            var produto = produtoVM.ToProduto();
            if (ModelState.IsValid)
            {
                if (produto.Id == 0)
                {
                    //TODO: validar dados de entrada
                    _produtoRepository.Add(produto);
                }
                else
                {
                    _produtoRepository.Edit(produto);
                }
                return RedirectToAction("Index");
            }

            var tipos = _tipoDeProdutoRepository.Get();
            ViewBag.Tipos = tipos;
            return View(produto);
        }

        public ActionResult DelProd(int id)
        {
            var produto = _produtoRepository.Get(id);
            if(produto != null)
            {
                _produtoRepository.Delete(produto); 
            } else {
                HttpNotFound();
            }
            return null;
        }

        protected override void Dispose(bool disposing)
        {}
    }
}

IS.Store.UI/Controllers/TesteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IS.Store.UI.Controllers
{
    public class TesteController:Controller
    {
        public string Ping()
        {
            return "Pong";
        }
    }
}

IS.Store.UI/Views/Conta/Login.cshtml
@model IS.Store.UI.ViewModels.Conta.Login.LoginVM
@{
    ViewBag.Title = "Login";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <form class="col-md-6 col-sm-12" method="post">
        <div class="form-group">
            <label>E-mail</label>
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", autofocus = "" })
            <small>
                @Html.ValidationMessageFor(model => model.Email, null, new { @class = "text-danger" })
            </small>
        </div>

        <div class="form-group">
            <label>Senha</label>
            @Html.PasswordFor(model => model.Senha, new { @class = "form-control" })
            <small>
                @Html.ValidationMessageFor(model => model.Senha, null, new { @class = "text-danger" })
            </small>
        </div>

        <div class="form-group form-check">
            @Html.CheckBoxFor(model => model.PermanecerLogado, new { @class = "form-check-input" })
            @Html.LabelFor(model => model.PermanecerLogado)
        </div>

        <div class="form-group">
            <button class="btn btn-outline-secondary">Login</button>
            <a href="@Url.Action("Index", "Home")" class="btn btn-outline-warning">Cancelar</a>
        </div>
    </form>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.validate.js"></script>
}

IS.Store.UI/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Página Inicial";
}
<h2>@ViewBag.Title</h2>
<p>
    Bem vindo ao e-commerce.
</p>

IS.Store.UI/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title</h2>
<p>Descrição do site</p>

IS.Store.UI/Views/Produtos/AddEdit.cshtml
@model IS.Store.UI.ViewModels.Produtos.AddEdit.ProdutoAddEditVM

@{
    ViewBag.Title = $"{(Model.Id == 0 ? "Adicionar" : "Editar")} Produto";
}

<h2>@ViewBag.Title</h2>
<form method="post">

    <div class="form-group">
        <label for="txtNome">Nome:</label>
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", autofocus = "" })
        <small>
            @Html.ValidationMessageFor(m => m.Nome, null, new { @class = "text-danger" })
        </small>
    </div>

    <div class="form-group">
        <label>Preço:</label>
        @Html.TextBoxFor(m => m.Preco, new { @class = "form-control" })
        <small>
            @Html.ValidationMessageFor(m => m.Preco, null, new { @class = "text-danger" })
        </small>
    </div>

    <div class="form-group">
        <label>Tipo:</label>
        @Html.DropDownListFor(m => m.TipoDeProdutoId, new SelectList(ViewBag.Tipos, "Id", "Nome"), "Selecione...", new { @class = "form-control" })
        <small>
            @Html.ValidationMessageFor(m => m.TipoDeProdutoId, null, new { @class = "text-danger" })
        </small>
    </div>

    <div class="form-group">
        <label>Quantidade:</label>
        @Html.TextBoxFor(m => m.Qtde, new { @class = "form-control" })
        <small>
            @Html.ValidationMessageFor(m => m.Qtde, null, new { @class = "text-danger" })
        </small>
    </div>

    <div>
        @Html.ValidationSummary(true)
    </div>

    <div class="form-group mt-3">
        <button class="btn btn-outline-success" type="submit" value="Salvar"><i class="fas fa-save"></i> Salvar</button>
        <a class="btn btn-outline-danger" href="@Url.Action("Index")"><i class="fas fa-window-close"></i> Cancelar</a>
    </div>

</form>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.validate.js"></script>
}

IS.Store.UI/Views/Produtos/Index.cshtml
@using IS.Store.UI.ViewModels.Produtos.Index
@{ 
    ViewBag.Title = "Listagem de Produtos";
}
<h2>@ViewBag.Title:</h2>

<div class="mb-3">
    <a class="btn btn-outline-primary" href="@Url.Action("AddEdit")">Novo Produto</a>
</div>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Preço</th>
                <th>Tipo</th>
                <th>Qtde</th>
                <th>Data do Cadastro</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (ProdutoIndexVM produto in Model)
            {
                <tr id="produto-@produto.Id">
                    <td>@produto.Nome</td>
                    <td>R$@produto.Preco.ToString("F2")</td>
                    <td>@produto.Tipo</td>
                    <td>@produto.Qtde</td>
                    <td>@produto.DataCadastro</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-outline-success btn-sm" href="@Url.Action("AddEdit", new { id = produto.Id })"><i class="fas fa-edit"></i>Editar</a>
                            <button class="btn btn-outline-danger btn-sm" onclick="DelProd(@produto.Id, '@produto.Nome')"><i class="fas fa-trash"></i>Excluir</button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div data-id="0" class="modal delModal" id="delModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir produto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir <strong><span id="nomeProdutoModal"></span></strong>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="ConfirmDelProd()">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function DelProd(id, nome) {
        $('#nomeProdutoModal').text(nome);
        $('#delModal').data('id', id).modal('show');
        $('.modal-backdrop').remove();
    }
    
    function ConfirmDelProd() {
        let id = $('#delModal').data('id');
        //XMLHTTPREQUEST
        let xhr = new XMLHttpRequest();
        const url = `/Produtos/DelProd/${id}`;

        xhr.onreadystatechange = function () {
            if (this.readyState === 4 && this.status === 404) {
                $('#delModal').data('id', '0').modal('hide');
                toastr.error('Erro na exclusão!', 'IS Store');
            }
            if (this.readyState === 4 && this.status === 200) {
                let tr = document.querySelector(`#produto-${id}`);
                if (tr != null) {
                    tr.remove();
                }
                //remover do HTML
                $('#delModal').data('id', '0').modal('hide');
                toastr.success('Produto excluido!', 'IS Store');
            }
        }
        xhr.open('get', url);
        xhr.send();
    }
</script>

IS.Store.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/all.min.css" rel="stylesheet" />
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link href="~/LandkitImport/assets/css/libs.bundle.css" rel="stylesheet" />
    <link href="~/LandkitImport/assets/css/theme.bundle.css" rel="stylesheet" />
    <title>IS Store | @ViewBag.Title</title>
</head>
<body>
    @Html.Partial("_menu")
    <div class="container mb-10">
        @RenderBody()
    </div>
    <footer class="footer mt-auto bg-info footer-custom">
        <div class="container">
            <span class="text-body-secondary">&copy;@DateTime.Now.Year I.S. Corporation.</span>
        </div>
    </footer>
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/LandkitImport/assets/js/theme.bundle.js"></script>
    <script src="~/LandkitImport/assets/js/vendor.bundle.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

IS.Store.UI/Views/Shared/_menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">IS Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="ml-0">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Produtos")">Produtos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Sobre", "Home")">Sobre</a>
                    </li>
                </ul>
            </div>
            <div class="mr-0">
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @User.Identity.Name
                            </a>

                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Trocar Senha</a></li>
                                <li><a class="dropdown-item" href="#">Perfil</a></li>
                                <div class="dropdown-divider" href="#"></div>
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Conta")">Logout</a></li>
                            </ul>
                        </div>
                    }
                    else
                    {

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Login", "Conta")">Efetuar Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</nav>